create extension if not exists pgmq;

create table if not exists public.stocks (
  stock_code text primary key check (stock_code ~ '^[0-9]{6}$'),
  name text not null,
  tier text not null,
  sector text not null,
  aliases jsonb not null default '[]'::jsonb,
  is_supported boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.news_articles (
  document_id text primary key,
  source text not null,
  title text not null,
  summary text not null default '',
  published_at timestamptz not null,
  canonical_url text not null default '',
  original_url text not null default '',
  source_url text not null default '',
  content_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists news_articles_published_at_idx
  on public.news_articles (published_at desc);

create table if not exists public.article_stocks (
  document_id text not null references public.news_articles(document_id) on delete cascade,
  stock_code text not null references public.stocks(stock_code) on delete cascade,
  query_id text not null,
  query_text text not null,
  query_type text not null,
  relation_type text not null,
  confidence double precision not null,
  status text not null check (status in ('eligible', 'candidate', 'rejected')),
  evidence jsonb not null default '[]'::jsonb,
  rule_version text not null,
  evaluated_at timestamptz not null,
  primary key (document_id, stock_code, query_id, rule_version)
);

create index if not exists article_stocks_stock_status_idx
  on public.article_stocks (stock_code, status);

create table if not exists public.stock_analysis_results (
  id bigint generated by default as identity primary key,
  stock_code text not null references public.stocks(stock_code) on delete cascade,
  model_version text not null,
  as_of date not null,
  article_count integer not null check (article_count >= 0),
  issue_count integer not null check (issue_count >= 0),
  result jsonb not null,
  analyzed_at timestamptz not null default now(),
  unique (stock_code, model_version, as_of)
);

create index if not exists stock_analysis_results_latest_idx
  on public.stock_analysis_results (stock_code, analyzed_at desc);

create table if not exists public.stock_analysis_state (
  stock_code text primary key references public.stocks(stock_code) on delete cascade,
  status text not null default 'idle'
    check (status in ('idle', 'queued', 'running', 'ready', 'insufficient_data', 'failed')),
  reason text,
  pending_article_count integer not null default 0,
  last_analyzed_at timestamptz,
  last_model_version text,
  retry_count integer not null default 0,
  error_message text,
  updated_at timestamptz not null default now()
);

alter table public.stocks enable row level security;
alter table public.news_articles enable row level security;
alter table public.article_stocks enable row level security;
alter table public.stock_analysis_results enable row level security;
alter table public.stock_analysis_state enable row level security;

drop policy if exists "public can read supported stocks" on public.stocks;
create policy "public can read supported stocks"
  on public.stocks for select to anon, authenticated
  using (is_supported);

drop policy if exists "public can read analysis results" on public.stock_analysis_results;
create policy "public can read analysis results"
  on public.stock_analysis_results for select to anon, authenticated
  using (true);

drop policy if exists "public can read analysis state" on public.stock_analysis_state;
create policy "public can read analysis state"
  on public.stock_analysis_state for select to anon, authenticated
  using (true);
